spring:
  application:
    name: micro-06-mssc-beer-inventory-service
  #jms properties
  artemis:
    user: artemis
    password: simetraehcapa
  #disable distributed tracing server ( dont want to send log into Zipkin )
  zipkin:
    enabled: false

server:
  port: 8082

logging:
  level:
    pl:
      kukla:
        krzys: DEBUG
