spring:
  application:
    name: micro-06-mssc-beer-inventory-service
  #jms properties
  artemis:
    user: artemis
    password: simetraehcapa
  #distributed tracing server
  zipkin:
    baseUrl: http://localhost:9411

server:
  port: 8082

logging:
  level:
    pl:
      kukla:
        krzys: DEBUG
