spring:
  application:
    name: micro-06-mssc-beer-inventory-service
  #jms properties
  artemis:
    user: artemis
    password: simetraehcapa

server:
  port: 8082

logging:
  level:
    pl:
      kukla:
        krzys: DEBUG
